people:
  security:
    jwt.secret: embi
  users:
    admin:
      username: admin
      password: 1234
    nonAdmin:
      username: user
      password: 1111
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org.zalando.logbook: TRACE