spring:
   profiles.active: dev

   liquibase.change-log: classpath:/db/changelog-master.xml
#   jackson.property-naming-strategy: SNAKE_CASE

logbook:
  exclude:
    - /actuator/health
   

        
   
              